/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashboardFrame;

import java.awt.Color;
import macamKoneksi.sessionLogin;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.ImageIcon;


/**
 *
 * @author mac
 */
public class dashboardUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form BackFrame
     */
    boolean cek = true;
    public dashboardUserFrame() {
        initComponents();
        namaSession.setText(sessionLogin.get_nama());
        popPanel.show(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel1 = new DashboardFrame.bgPanel();
        headerPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        namaSession = new javax.swing.JLabel();
        hamMenu = new javax.swing.JLabel();
        popPanel = new javax.swing.JPanel();
        categoryPanel = new javax.swing.JPanel();
        CategoryLabel = new javax.swing.JLabel();
        cartPanel = new javax.swing.JPanel();
        cartLabel = new javax.swing.JLabel();
        wishlistPanel = new javax.swing.JPanel();
        wishlistLabel = new javax.swing.JLabel();
        contactusPanel = new javax.swing.JPanel();
        contactusLabel = new javax.swing.JLabel();
        productHighlightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productHighlightPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        headerPanel.setBackground(new java.awt.Color(3, 166, 44));

        logoLabel.setFont(new java.awt.Font("Glitten", 1, 14)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/caduceus.png"))); // NOI18N
        logoLabel.setText("APOTEK MEDIKA SENTOSA");

        namaSession.setFont(new java.awt.Font("Glitten", 0, 14)); // NOI18N
        namaSession.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        namaSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/user.png"))); // NOI18N
        namaSession.setText("NAMA");
        namaSession.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        hamMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/menu.png"))); // NOI18N
        hamMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hamMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hamMenu)
                .addGap(18, 18, 18)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaSession, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaSession, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hamMenu)
                .addGap(24, 24, 24))
        );

        popPanel.setBackground(new java.awt.Color(204, 204, 204));
        popPanel.setOpaque(false);
        popPanel.setLayout(new javax.swing.BoxLayout(popPanel, javax.swing.BoxLayout.PAGE_AXIS));

        categoryPanel.setBackground(new java.awt.Color(204, 255, 204));
        categoryPanel.setMaximumSize(new java.awt.Dimension(249, 82));
        categoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoryPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoryPanelMouseExited(evt);
            }
        });
        categoryPanel.setLayout(new java.awt.CardLayout(15, 15));

        CategoryLabel.setFont(new java.awt.Font("Glitten", 1, 13)); // NOI18N
        CategoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CategoryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/dashboard.png"))); // NOI18N
        CategoryLabel.setText("CATEGORY");
        categoryPanel.add(CategoryLabel, "card2");

        popPanel.add(categoryPanel);
        categoryPanel.getAccessibleContext().setAccessibleName("");

        cartPanel.setBackground(new java.awt.Color(204, 255, 204));
        cartPanel.setLayout(new java.awt.CardLayout());

        cartLabel.setBackground(new java.awt.Color(204, 255, 204));
        cartLabel.setFont(new java.awt.Font("Glitten", 0, 13)); // NOI18N
        cartLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/shopping-cart.png"))); // NOI18N
        cartLabel.setText("CART");
        cartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartLabelMouseExited(evt);
            }
        });
        cartPanel.add(cartLabel, "card2");

        popPanel.add(cartPanel);

        wishlistPanel.setBackground(new java.awt.Color(204, 255, 204));
        wishlistPanel.setLayout(new java.awt.CardLayout());

        wishlistLabel.setFont(new java.awt.Font("Glitten", 0, 13)); // NOI18N
        wishlistLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wishlistLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/heart.png"))); // NOI18N
        wishlistLabel.setText("WISHLIST");
        wishlistLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wishlistLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wishlistLabelMouseExited(evt);
            }
        });
        wishlistPanel.add(wishlistLabel, "card2");

        popPanel.add(wishlistPanel);

        contactusPanel.setBackground(new java.awt.Color(204, 255, 204));
        contactusPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactusPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactusPanelMouseExited(evt);
            }
        });
        contactusPanel.setLayout(new java.awt.CardLayout());

        contactusLabel.setFont(new java.awt.Font("Glitten", 0, 13)); // NOI18N
        contactusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/contact-mail.png"))); // NOI18N
        contactusLabel.setText("CONTACT US");
        contactusPanel.add(contactusLabel, "card2");

        popPanel.add(contactusPanel);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/pillsProduct.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/pillsBotolProduct.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardFrame/gambar/pillsBotolProduct.jpg"))); // NOI18N

        javax.swing.GroupLayout productHighlightPanelLayout = new javax.swing.GroupLayout(productHighlightPanel);
        productHighlightPanel.setLayout(productHighlightPanelLayout);
        productHighlightPanelLayout.setHorizontalGroup(
            productHighlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productHighlightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(productHighlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        productHighlightPanelLayout.setVerticalGroup(
            productHighlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productHighlightPanelLayout.createSequentialGroup()
                .addGroup(productHighlightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productHighlightPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(productHighlightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout productHighlightPanel1Layout = new javax.swing.GroupLayout(productHighlightPanel1);
        productHighlightPanel1.setLayout(productHighlightPanel1Layout);
        productHighlightPanel1Layout.setHorizontalGroup(
            productHighlightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        productHighlightPanel1Layout.setVerticalGroup(
            productHighlightPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgPanel1Layout = new javax.swing.GroupLayout(bgPanel1);
        bgPanel1.setLayout(bgPanel1Layout);
        bgPanel1Layout.setHorizontalGroup(
            bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(popPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productHighlightPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productHighlightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bgPanel1Layout.setVerticalGroup(
            bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanel1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(popPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productHighlightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productHighlightPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bgPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void changeColor (JPanel panel, Color hex){
        panel.setBackground(hex);
    }
    
    public  void changeIcon (JLabel ham, String resource){
        ImageIcon ikon = new ImageIcon (getClass().getResource(resource));
        ham.setIcon(ikon);
    }
    
    public void popMenu (JPanel menuPop , boolean dashboard, JLabel hamMenu){
        if (dashboard == true) {
            menuPop.setPreferredSize(new Dimension (249, 329));
            changeIcon(hamMenu, "/DashboardFrame/gambar/close.png");
            menuPop.show(true);
            
        }
        else {
            menuPop.show(false);
            changeIcon(hamMenu, "/DashboardFrame/gambar/menu.png");
        }
    }
    
    private void hamMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hamMenuMouseClicked
        
        if (cek == true) {
            popMenu(popPanel, cek, hamMenu);
            SwingUtilities.updateComponentTreeUI(this);
            cek = false;
        }
        else {
            popMenu(popPanel, cek, hamMenu);
            SwingUtilities.updateComponentTreeUI(this);
            cek = true;
        }
    }//GEN-LAST:event_hamMenuMouseClicked

    private void categoryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryPanelMouseEntered
        // TODO add your handling code here:
        changeColor(categoryPanel, new Color(3,166,44));
    }//GEN-LAST:event_categoryPanelMouseEntered

    private void categoryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryPanelMouseExited
        // TODO add your handling code here:
        changeColor(categoryPanel, new Color(204,255,204));
    }//GEN-LAST:event_categoryPanelMouseExited

    private void cartLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartLabelMouseEntered
        // TODO add your handling code here:
        changeColor(cartPanel, new Color(3,166,44));
    }//GEN-LAST:event_cartLabelMouseEntered

    private void cartLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartLabelMouseExited
        // TODO add your handling code here:
        changeColor(cartPanel, new Color(204,255,204));
    }//GEN-LAST:event_cartLabelMouseExited

    private void wishlistLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistLabelMouseEntered
        // TODO add your handling code here:
        changeColor(wishlistPanel, new Color(3,166,44));
    }//GEN-LAST:event_wishlistLabelMouseEntered

    private void wishlistLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistLabelMouseExited
        // TODO add your handling code here:
        changeColor(wishlistPanel, new Color(204,255,204));
    }//GEN-LAST:event_wishlistLabelMouseExited

    private void contactusPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactusPanelMouseEntered
        // TODO add your handling code here:
        changeColor(contactusPanel, new Color(3,166,44));
    }//GEN-LAST:event_contactusPanelMouseEntered

    private void contactusPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactusPanelMouseExited
        // TODO add your handling code here:
        changeColor(contactusPanel, new Color(204,255,204));
    }//GEN-LAST:event_contactusPanelMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryLabel;
    private DashboardFrame.bgPanel bgPanel1;
    private javax.swing.JLabel cartLabel;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JLabel contactusLabel;
    private javax.swing.JPanel contactusPanel;
    private javax.swing.JLabel hamMenu;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel namaSession;
    private javax.swing.JPanel popPanel;
    private javax.swing.JPanel productHighlightPanel;
    private javax.swing.JPanel productHighlightPanel1;
    private javax.swing.JLabel wishlistLabel;
    private javax.swing.JPanel wishlistPanel;
    // End of variables declaration//GEN-END:variables
}
