/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegisterFrame;

import LoginFrame.loginUserFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mac
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form BackFrame
     */
    public RegisterFrame() {
        initComponents();
        detectWrong.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel2 = new LoginFrame.bgPanel();
        dasarForm = new javax.swing.JPanel();
        backLoginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        headPanel = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        unameKet = new javax.swing.JLabel();
        unameField = new javax.swing.JTextField();
        unameKet2 = new javax.swing.JLabel();
        reunameField = new javax.swing.JTextField();
        hpKet = new javax.swing.JLabel();
        nohpFIeld = new javax.swing.JTextField();
        passKet = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passKet2 = new javax.swing.JLabel();
        repasswordField = new javax.swing.JPasswordField();
        detectWrong = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        dasarForm.setBackground(new java.awt.Color(3, 166, 44));

        backLoginButton.setFont(new java.awt.Font("LEMON MILK", 0, 10)); // NOI18N
        backLoginButton.setForeground(new java.awt.Color(0, 153, 0));
        backLoginButton.setText("Back to Login");
        backLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginButtonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("LEMON MILK", 0, 13)); // NOI18N
        registerButton.setForeground(new java.awt.Color(0, 153, 0));
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        headPanel.setBackground(new java.awt.Color(3, 166, 44));

        registerLabel.setBackground(new java.awt.Color(0, 255, 0));
        registerLabel.setFont(new java.awt.Font("LEMON MILK", 3, 18)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("REGISTER");
        registerLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addComponent(registerLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        formPanel.setBackground(new java.awt.Color(3, 166, 44));
        formPanel.setLayout(new java.awt.GridLayout(10, 1, 10, 5));

        unameKet.setFont(new java.awt.Font("LEMON MILK", 0, 13)); // NOI18N
        unameKet.setForeground(new java.awt.Color(255, 255, 255));
        unameKet.setText("USERNAME");
        formPanel.add(unameKet);

        unameField.setMaximumSize(new java.awt.Dimension(168, 25));
        unameField.setPreferredSize(new java.awt.Dimension(168, 25));
        formPanel.add(unameField);

        unameKet2.setFont(new java.awt.Font("LEMON MILK", 0, 13)); // NOI18N
        unameKet2.setForeground(new java.awt.Color(255, 255, 255));
        unameKet2.setText("re-type USERNAME");
        formPanel.add(unameKet2);

        reunameField.setPreferredSize(new java.awt.Dimension(168, 25));
        reunameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reunameFieldKeyReleased(evt);
            }
        });
        formPanel.add(reunameField);

        hpKet.setFont(new java.awt.Font("LEMON MILK", 0, 13)); // NOI18N
        hpKet.setForeground(new java.awt.Color(255, 255, 255));
        hpKet.setText("HANDPHONE");
        formPanel.add(hpKet);

        nohpFIeld.setPreferredSize(new java.awt.Dimension(168, 25));
        nohpFIeld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nohpFIeldKeyReleased(evt);
            }
        });
        formPanel.add(nohpFIeld);

        passKet.setFont(new java.awt.Font("LEMON MILK", 0, 13)); // NOI18N
        passKet.setForeground(new java.awt.Color(255, 255, 255));
        passKet.setText("PASSWORD");
        formPanel.add(passKet);

        passwordField.setToolTipText("");
        formPanel.add(passwordField);

        passKet2.setFont(new java.awt.Font("LEMON MILK", 0, 13)); // NOI18N
        passKet2.setForeground(new java.awt.Color(255, 255, 255));
        passKet2.setText("re-type PASSWORD");
        formPanel.add(passKet2);

        repasswordField.setToolTipText("");
        repasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                repasswordFieldKeyReleased(evt);
            }
        });
        formPanel.add(repasswordField);

        detectWrong.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        detectWrong.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout dasarFormLayout = new javax.swing.GroupLayout(dasarForm);
        dasarForm.setLayout(dasarFormLayout);
        dasarFormLayout.setHorizontalGroup(
            dasarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dasarFormLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(dasarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarFormLayout.createSequentialGroup()
                        .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarFormLayout.createSequentialGroup()
                        .addComponent(backLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarFormLayout.createSequentialGroup()
                        .addGroup(dasarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detectWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))))
        );
        dasarFormLayout.setVerticalGroup(
            dasarFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarFormLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detectWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegisterFrame/Sign up-amico.png"))); // NOI18N

        javax.swing.GroupLayout bgPanel2Layout = new javax.swing.GroupLayout(bgPanel2);
        bgPanel2.setLayout(bgPanel2Layout);
        bgPanel2Layout.setHorizontalGroup(
            bgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dasarForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgPanel2Layout.setVerticalGroup(
            bgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(logoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dasarForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        String regisuserName = unameField.getText();
        String regisreuserName = reunameField.getText();
        String regishpUser = nohpFIeld.getText();
        String regispassword = passwordField.getText();
        String regisrePassword = repasswordField.getText();
        
        boolean samakah = regisuserName.equals(regisreuserName);
        boolean samapass = regispassword.equals(regisrePassword);
                
        if (!samakah) {
            JOptionPane.showMessageDialog(null, "UserName Berbeda");
        } 
        else if (!samapass) {
            JOptionPane.showMessageDialog(null, "Password Berbeda");
        }
        else {
            try{
                Connection konekDatabase = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/db_apotikMedikaSentoasa", "root", "kadekmontana050703");

                PreparedStatement regisQuery = (PreparedStatement) konekDatabase.prepareStatement("insert into tb_user (user_name, hp_user, pass_user) values (?,?,?)");
                
                regisQuery.setString(1, regisuserName);
                regisQuery.setString(2, regishpUser);
                regisQuery.setString(3, regispassword);
                regisQuery.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Registered Successfully");
                konekDatabase.close();
            } catch (SQLException sqlException){
                sqlException.printStackTrace();
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void backLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginButtonActionPerformed
        // TODO add your handling code here:
        loginUserFrame keLogin = new loginUserFrame();
        keLogin.show();
        dispose();
    }//GEN-LAST:event_backLoginButtonActionPerformed

    private void repasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repasswordFieldKeyReleased
        // TODO add your handling code here:
        String regispassword = passwordField.getText();
        String regisrePassword = repasswordField.getText();
        
        if (regispassword.equals(regisrePassword)) {
            detectWrong.setText(" ");
        }
        else if (!regispassword.equals(regisrePassword)) {
            detectWrong.setText("PASSWORD TIDAK SAMA!");
        }
    }//GEN-LAST:event_repasswordFieldKeyReleased

    private void reunameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reunameFieldKeyReleased
        // TODO add your handling code here:
        String regisuserName = unameField.getText();
        String regisreuserName = reunameField.getText();
        
        if (regisuserName.equals(regisreuserName)) {
            detectWrong.setText(" ");
        }
        else if (!regisuserName.equals(regisreuserName)) {
            detectWrong.setText("USERNAME TIDAK SAMA!");
        }
    }//GEN-LAST:event_reunameFieldKeyReleased

    private void nohpFIeldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nohpFIeldKeyReleased
        // TODO add your handling code here:
        String noHP = nohpFIeld.getText();
        int panjang = (int) noHP.length();
        if ( panjang > 13 || panjang < 10) {
            detectWrong.setText("FORMAT HP SALAH");
        } else {
            detectWrong.setText("");
        }
    }//GEN-LAST:event_nohpFIeldKeyReleased

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLoginButton;
    private LoginFrame.bgPanel bgPanel2;
    private javax.swing.JPanel dasarForm;
    private javax.swing.JLabel detectWrong;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JLabel hpKet;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField nohpFIeld;
    private javax.swing.JLabel passKet;
    private javax.swing.JLabel passKet2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPasswordField repasswordField;
    private javax.swing.JTextField reunameField;
    private javax.swing.JTextField unameField;
    private javax.swing.JLabel unameKet;
    private javax.swing.JLabel unameKet2;
    // End of variables declaration//GEN-END:variables
}
